//
//  errors.h
//  rem
//
//  Created by Erik A Johnson on 10/29/19 - 12/09/2019.
//  Copyright © 2019 Erik A Johnson. All rights reserved.
//

#ifndef errors_h
#define errors_h

#define MY_ERROR_DOMAIN @"edu.usc.johnsone.rem"

typedef enum _ExitStatus {
    EXIT_CLEAN = 200,
    EXIT_FATAL = 201,
    EXIT_NORMAL = 0,
    EXIT_FAIL_ALLOC,
    EXIT_FAIL_NOINIT,
    EXIT_AUTH_UNKNOWNRESPONSE,
    EXIT_ACCESS_DENIED,
    EXIT_ACCESS_RESTRICTED,
    EXIT_ACCESS_NOTGRANTED,
    EXIT_ACCESS_TIMEDOUT,
    EXIT_GEOCODE_TIMEDOUT,
    EXIT_CMD_UNKNOWN,
    EXIT_INVARG_NOSUCHCALENDAR,
    EXIT_INVARG_NOTALLCALENDARS,
    EXIT_INVARG_NOID,
    EXIT_INVARG_EMPTYCALENDAR,
    EXIT_INVARG_IDRANGE,
    EXIT_INVARG_SNOOZEMISSING,
    EXIT_INVARG_BADSWITCH,
    EXIT_INVARG_BADPRIORITY,
    EXIT_INVARG_BADDURATION,
    EXIT_INVARG_BADSNOOZE,
    EXIT_INVARG_BADDATADETECTOR,
    EXIT_INVARG_BADDATE,
    EXIT_INVARG_BADTITLE,
    EXIT_INVARG_BADTITLEREGEX,
    EXIT_INVARG_BADLOCATION,
    EXIT_INVARG_ABSORREL,
    EXIT_FAIL_ADD,
    EXIT_FAIL_RM,
    EXIT_FAIL_COMPLETE,
    EXIT_FAIL_SNOOZE,
    EXIT_SNOOZE_NOALARMS,
    EXIT_SNOOZE_ALREADYCOMPLETED,
    EXIT_SNOOZE_NOTSNOOZING,
} ExitStatus;


#endif /* errors_h */
